<template>
    <div>
      <card :title="'Action icons'">
        <v-icon>3d_rotation</v-icon>
        <v-icon>accessibility</v-icon>
        <v-icon>accessible</v-icon>
        <v-icon>account_balance</v-icon>
        <v-icon>account_balance_wallet</v-icon>
        <v-icon>account_box</v-icon>
        <v-icon>account_circle</v-icon>
        <v-icon>add_shopping_cart</v-icon>
        <v-icon>alarm</v-icon>
        <v-icon>alarm_add</v-icon>
        <v-icon>alarm_off</v-icon>
        <v-icon>alarm_on</v-icon>
        <v-icon>all_out</v-icon>
        <v-icon>android</v-icon>
        <v-icon>announcement</v-icon>
        <v-icon>aspect_ratio</v-icon>
        <v-icon>assessment</v-icon>
        <v-icon>assignment</v-icon>
        <v-icon>assignment_ind</v-icon>
        <v-icon>assignment_late</v-icon>
        <v-icon>assignment_return</v-icon>
        <v-icon>assignment_returned</v-icon>
        <v-icon>assignment_turned_in</v-icon>
        <v-icon>autorenew</v-icon>
        <v-icon>backup</v-icon>
        <v-icon>book</v-icon>
        <v-icon>bookmark</v-icon>
        <v-icon>bookmark_outline</v-icon>
        <v-icon>bug_report</v-icon>
        <v-icon>build</v-icon>
        <v-icon>cached</v-icon>
        <v-icon>camera_enhanced</v-icon>
        <v-icon>card_giftcard</v-icon>
        <v-icon>card_membership</v-icon>
        <v-icon>card_travel</v-icon>
        <v-icon>change_history</v-icon>
        <v-icon>check_circle</v-icon>
        <v-icon>chrome_reader_mode</v-icon>
        <v-icon>class</v-icon>
        <v-icon>code</v-icon>
        <v-icon>compare_arrows</v-icon>
        <v-icon>copyright</v-icon>
        <v-icon>credit_card</v-icon>
        <v-icon>dashboard</v-icon>
        <v-icon>date_range</v-icon>
        <v-icon>delete</v-icon>
        <v-icon>delete_forever</v-icon>
        <v-icon>description</v-icon>
        <v-icon>dns</v-icon>
        <v-icon>done</v-icon>
        <v-icon>done_all</v-icon>
        <v-icon>donut_large</v-icon>
        <v-icon>donut_small</v-icon>
        <v-icon>eject</v-icon>
        <v-icon>euro_symbol</v-icon>
        <v-icon>event</v-icon>
        <v-icon>event_seat</v-icon>
        <v-icon>exit_to_app</v-icon>
        <v-icon>explore</v-icon>
        <v-icon>extension</v-icon>
        <v-icon>face</v-icon>
        <v-icon>favorite</v-icon>
        <v-icon>favorite_border</v-icon>
        <v-icon>feedback</v-icon>
        <v-icon>find_in_page</v-icon>
        <v-icon>find_replace</v-icon>
        <v-icon>fingerprint</v-icon>
        <v-icon>flight_land</v-icon>
        <v-icon>flight_takeoff</v-icon>
        <v-icon>flip_to_back</v-icon>
        <v-icon>flip_to_front</v-icon>
        <v-icon>g_translate</v-icon>
        <v-icon>gavel</v-icon>
        <v-icon>get_app</v-icon>
        <v-icon>gif</v-icon>
        <v-icon>grade</v-icon>
        <v-icon>group_work</v-icon>
        <v-icon>help</v-icon>
        <v-icon>help_outline</v-icon>
        <v-icon>highlight_off</v-icon>
        <v-icon>history</v-icon>
        <v-icon>home</v-icon>
        <v-icon>hourglass_empty</v-icon>
        <v-icon>hourglass_full</v-icon>
        <v-icon>http</v-icon>
        <v-icon>https</v-icon>
        <v-icon>important_devices</v-icon>
        <v-icon>info</v-icon>
        <v-icon>info_outline</v-icon>
        <v-icon>input</v-icon>
        <v-icon>invert_colors</v-icon>
        <v-icon>label</v-icon>
        <v-icon>label_outline</v-icon>
        <v-icon>language</v-icon>
        <v-icon>launch</v-icon>
        <v-icon>lightbulb_outline</v-icon>
        <v-icon>line_style</v-icon>
        <v-icon>line_weight</v-icon>
        <v-icon>list</v-icon>
        <v-icon>lock</v-icon>
        <v-icon>lock_open</v-icon>
        <v-icon>lock_outline</v-icon>
        <v-icon>loyalty</v-icon>
        <v-icon>markunread_mailbox</v-icon>
        <v-icon>motorcycle</v-icon>
        <v-icon>note_add</v-icon>
        <v-icon>offline_pin</v-icon>
        <v-icon>opacity</v-icon>
        <v-icon>open_in_browser</v-icon>
        <v-icon>open_in_new</v-icon>
        <v-icon>open_with</v-icon>
        <v-icon>pageview</v-icon>
        <v-icon>pan_tool</v-icon>
        <v-icon>payment</v-icon>
        <v-icon>perm_camera_mic</v-icon>
        <v-icon>perm_contact_calendar</v-icon>
        <v-icon>perm_data_setting</v-icon>
        <v-icon>perm_device_inforvion</v-icon>
        <v-icon>perm_identity</v-icon>
        <v-icon>perm_media</v-icon>
        <v-icon>perm_phone_msg</v-icon>
        <v-icon>perm_scan_wifi</v-icon>
        <v-icon>pets</v-icon>
        <v-icon>picture_in_picture</v-icon>
        <v-icon>picture_in_picture_alt</v-icon>
        <v-icon>play_for_work</v-icon>
        <v-icon>polymer</v-icon>
        <v-icon>power_settings_new</v-icon>
        <v-icon>pregnant_woman</v-icon>
        <v-icon>print</v-icon>
        <v-icon>query_builder</v-icon>
        <v-icon>question_answer</v-icon>
        <v-icon>receipt</v-icon>
        <v-icon>record_voice_over</v-icon>
        <v-icon>redeem</v-icon>
        <v-icon>remove_shopping_cart</v-icon>
        <v-icon>reorder</v-icon>
        <v-icon>report_problem</v-icon>
        <v-icon>restore</v-icon>
        <v-icon>restore_page</v-icon>
        <v-icon>room</v-icon>
        <v-icon>rounded_corner</v-icon>
        <v-icon>rowing</v-icon>
        <v-icon>schedule</v-icon>
        <v-icon>search</v-icon>
        <v-icon>settings</v-icon>
        <v-icon>settings_applications</v-icon>
        <v-icon>settings_backup_restore</v-icon>
        <v-icon>settings_bluetooth</v-icon>
        <v-icon>settings_brightness</v-icon>
        <v-icon>settings_cell</v-icon>
        <v-icon>settings_ethernet</v-icon>
        <v-icon>settings_input_antenna</v-icon>
        <v-icon>settings_input_component</v-icon>
        <v-icon>settings_input_composite</v-icon>
        <v-icon>settings_input_hdmi</v-icon>
        <v-icon>settings_input_svideo</v-icon>
        <v-icon>settings_overscan</v-icon>
        <v-icon>settings_phone</v-icon>
        <v-icon>settings_power</v-icon>
        <v-icon>settings_remote</v-icon>
        <v-icon>settings_voice</v-icon>
        <v-icon>shop</v-icon>
        <v-icon>shop_two</v-icon>
        <v-icon>shopping_basket</v-icon>
        <v-icon>shopping_cart</v-icon>
        <v-icon>speaker_notes</v-icon>
        <v-icon>speaker_notes_off</v-icon>
        <v-icon>spellcheck</v-icon>
        <v-icon>star_rate</v-icon>
        <v-icon>stars</v-icon>
        <v-icon>store</v-icon>
        <v-icon>subject</v-icon>
        <v-icon>supervisor_account</v-icon>
        <v-icon>swap_horiz</v-icon>
        <v-icon>swap_vert</v-icon>
        <v-icon>swap_vertial_circle</v-icon>
        <v-icon>system_update_alt</v-icon>
        <v-icon>tab</v-icon>
        <v-icon>tab_unselected</v-icon>
        <v-icon>theaters</v-icon>
        <v-icon>thumb_down</v-icon>
        <v-icon>thumb_up</v-icon>
        <v-icon>thumbs_up_down</v-icon>
        <v-icon>timeline</v-icon>
        <v-icon>toc</v-icon>
        <v-icon>today</v-icon>
        <v-icon>toll</v-icon>
        <v-icon>touch_app</v-icon>
        <v-icon>track_changes</v-icon>
        <v-icon>translate</v-icon>
        <v-icon>trending_down</v-icon>
        <v-icon>trending_flat</v-icon>
        <v-icon>trending_up</v-icon>
        <v-icon>turned_in</v-icon>
        <v-icon>turned_in_not</v-icon>
        <v-icon>update</v-icon>
        <v-icon>verified_user</v-icon>
        <v-icon>view_agenda</v-icon>
        <v-icon>view_array</v-icon>
        <v-icon>view_carousel</v-icon>
        <v-icon>view_column</v-icon>
        <v-icon>view_day</v-icon>
        <v-icon>view_headline</v-icon>
        <v-icon>view_list</v-icon>
        <v-icon>view_module</v-icon>
        <v-icon>view_quilt</v-icon>
        <v-icon>view_stream</v-icon>
        <v-icon>view_week</v-icon>
        <v-icon>visibility</v-icon>
        <v-icon>visibility_off</v-icon>
        <v-icon>watch_later</v-icon>
        <v-icon>work</v-icon>
        <v-icon>youtube_searched_for</v-icon>
        <v-icon>zoom_in</v-icon>
        <v-icon>zoom_out</v-icon>
      </card>
      <card :title="'Alert icons'">
        <v-icon>add_alert</v-icon>
        <v-icon>error</v-icon>
        <v-icon>error_outline</v-icon>
        <v-icon>warning</v-icon>
      </card>
      <card :title="'Av icons'">
        <v-icon>add_to_queue</v-icon>
        <v-icon>airplay</v-icon>
        <v-icon>album</v-icon>
        <v-icon>art_track</v-icon>
        <v-icon>av_timer</v-icon>
        <v-icon>branding_watermark</v-icon>
        <v-icon>call_to_action</v-icon>
        <v-icon>closed_caption</v-icon>
        <v-icon>equalizer</v-icon>
        <v-icon>explicit</v-icon>
        <v-icon>fast_forward</v-icon>
        <v-icon>fast_rewind</v-icon>
        <v-icon>featured_play_list</v-icon>
        <v-icon>featured_video</v-icon>
        <v-icon>fiber_manual_record</v-icon>
        <v-icon>forward_10</v-icon>
        <v-icon>forward_30</v-icon>
        <v-icon>forward_5</v-icon>
        <v-icon>games</v-icon>
        <v-icon>hd</v-icon>
        <v-icon>hearing</v-icon>
        <v-icon>high_quality</v-icon>
        <v-icon>my_library_add</v-icon>
        <v-icon>my_library_books</v-icon>
        <v-icon>my_library_music</v-icon>
        <v-icon>loop</v-icon>
        <v-icon>mic</v-icon>
        <v-icon>mic_none</v-icon>
        <v-icon>mic_off</v-icon>
        <v-icon>movie</v-icon>
        <v-icon>music_video</v-icon>
        <v-icon>new_releases</v-icon>
        <v-icon>not_interested</v-icon>
        <v-icon>note</v-icon>
        <v-icon>pause</v-icon>
        <v-icon>pause_circle_filled</v-icon>
        <v-icon>pause_circle_outline</v-icon>
        <v-icon>play_arrow</v-icon>
        <v-icon>play_circle_fill</v-icon>
        <v-icon>play_circle_outline</v-icon>
        <v-icon>playlist_add</v-icon>
        <v-icon>playlist_add_check</v-icon>
        <v-icon>playlist_play</v-icon>
        <v-icon>queue</v-icon>
        <v-icon>queue_music</v-icon>
        <v-icon>queue_play_next</v-icon>
        <v-icon>radio</v-icon>
        <v-icon>recent_actors</v-icon>
        <v-icon>remove_from_queue</v-icon>
        <v-icon>repeat</v-icon>
        <v-icon>repeat_one</v-icon>
        <v-icon>replay</v-icon>
        <v-icon>replay_10</v-icon>
        <v-icon>replay_30</v-icon>
        <v-icon>replay_5</v-icon>
        <v-icon>shuffle</v-icon>
        <v-icon>skip_next</v-icon>
        <v-icon>skip_previous</v-icon>
        <v-icon>slow_motion_video</v-icon>
        <v-icon>snooze</v-icon>
        <v-icon>sort_by_alpha</v-icon>
        <v-icon>stop</v-icon>
        <v-icon>subscriptions</v-icon>
        <v-icon>subtitles</v-icon>
        <v-icon>surround_sound</v-icon>
        <v-icon>video_call</v-icon>
        <v-icon>video_label</v-icon>
        <v-icon>video_library</v-icon>
        <v-icon>videocam</v-icon>
        <v-icon>videocam_off</v-icon>
        <v-icon>volume_down</v-icon>
        <v-icon>volume_mute</v-icon>
        <v-icon>volume_off</v-icon>
        <v-icon>volume_up</v-icon>
        <v-icon>web</v-icon>
        <v-icon>web_asset</v-icon>
      </card>
      <card :title="'Cummunikation icons'">
        <v-icon>business</v-icon>
        <v-icon>call</v-icon>
        <v-icon>call_end</v-icon>
        <v-icon>call_made</v-icon>
        <v-icon>call_merge</v-icon>
        <v-icon>call_missed</v-icon>
        <v-icon>call_missed_outgoing</v-icon>
        <v-icon>call_received</v-icon>
        <v-icon>call_split</v-icon>
        <v-icon>chat</v-icon>
        <v-icon>chat_bubble</v-icon>
        <v-icon>chat_bubble_outline</v-icon>
        <v-icon>clear_all</v-icon>
        <v-icon>comment</v-icon>
        <v-icon>contact_mail</v-icon>
        <v-icon>contact_phone</v-icon>
        <v-icon>contacts</v-icon>
        <v-icon>dialer_sip</v-icon>
        <v-icon>dialpad</v-icon>
        <v-icon>email</v-icon>
        <v-icon>forum</v-icon>
        <v-icon>import_contacts</v-icon>
        <v-icon>import_export</v-icon>
        <v-icon>invert_colors_off</v-icon>
        <v-icon>live_help</v-icon>
        <v-icon>location_off</v-icon>
        <v-icon>location_on</v-icon>
        <v-icon>mail_outline</v-icon>
        <v-icon>message</v-icon>
        <v-icon>no_sim</v-icon>
        <v-icon>phone</v-icon>
        <v-icon>phonelink_erase</v-icon>
        <v-icon>phonelink_lock</v-icon>
        <v-icon>phonelink_ring</v-icon>
        <v-icon>phonelink_setup</v-icon>
        <v-icon>portable_wifi_off</v-icon>
        <v-icon>present_to_all</v-icon>
        <v-icon>ring_volume</v-icon>
        <v-icon>rss_feed</v-icon>
        <v-icon>screen_share</v-icon>
        <v-icon>stay_current_landscape</v-icon>
        <v-icon>stay_current_portrait</v-icon>
        <v-icon>stay_primary_landscape</v-icon>
        <v-icon>stay_primary_portrait</v-icon>
        <v-icon>stop_screen_share</v-icon>
        <v-icon>swap_calls</v-icon>
        <v-icon>textsms</v-icon>
        <v-icon>voicemail</v-icon>
        <v-icon>vpn_key</v-icon>
      </card>
      <card :title="'Content icons'">
        <v-icon>add</v-icon>
        <v-icon>add_box</v-icon>
        <v-icon>add_circle</v-icon>
        <v-icon>add_circle_outline</v-icon>
        <v-icon>archive</v-icon>
        <v-icon>backspace</v-icon>
        <v-icon>block</v-icon>
        <v-icon>clear</v-icon>
        <v-icon>content_copy</v-icon>
        <v-icon>content_cut</v-icon>
        <v-icon>content_paste</v-icon>
        <v-icon>create</v-icon>
        <v-icon>delete_sweep</v-icon>
        <v-icon>drafts</v-icon>
        <v-icon>filter_list</v-icon>
        <v-icon>flag</v-icon>
        <v-icon>font_download</v-icon>
        <v-icon>forward</v-icon>
        <v-icon>gesture</v-icon>
        <v-icon>inbox</v-icon>
        <v-icon>link</v-icon>
        <v-icon>low_priority</v-icon>
        <v-icon>mail</v-icon>
        <v-icon>markunread</v-icon>
        <v-icon>move_to_inbox</v-icon>
        <v-icon>next_week</v-icon>
        <v-icon>redo</v-icon>
        <v-icon>remove</v-icon>
        <v-icon>remove_circle</v-icon>
        <v-icon>remove_circle_outline</v-icon>
        <v-icon>reply</v-icon>
        <v-icon>reply_all</v-icon>
        <v-icon>report</v-icon>
        <v-icon>save</v-icon>
        <v-icon>select_all</v-icon>
        <v-icon>send</v-icon>
        <v-icon>sort</v-icon>
        <v-icon>text_forv</v-icon>
        <v-icon>unarchive</v-icon>
        <v-icon>undo</v-icon>
        <v-icon>weekend</v-icon>
      </card>
      <card :title="'Device icons'">
        <v-icon>access_alarms</v-icon>
        <v-icon>access_alarm</v-icon>
        <v-icon>access_time</v-icon>
        <v-icon>add_alarm</v-icon>
        <v-icon>airplanemode_on</v-icon>
        <v-icon>airplanemode_inactive</v-icon>
        <v-icon>battery_charging_full</v-icon>
        <v-icon>battery_full</v-icon>
        <v-icon>battery_std</v-icon>
        <v-icon>battery_unknown</v-icon>
        <v-icon>bluetooth</v-icon>
        <v-icon>bluetooth_connected</v-icon>
        <v-icon>bluetooth_disabled</v-icon>
        <v-icon>bluetooth_searching</v-icon>
        <v-icon>brightness_auto</v-icon>
        <v-icon>brightness_high</v-icon>
        <v-icon>brightness_low</v-icon>
        <v-icon>brightness_medium</v-icon>
        <v-icon>data_usage</v-icon>
        <v-icon>developer_mode</v-icon>
        <v-icon>devices</v-icon>
        <v-icon>dvr</v-icon>
        <v-icon>gps_fixed</v-icon>
        <v-icon>gps_not_fixed</v-icon>
        <v-icon>gps_off</v-icon>
        <v-icon>graphic_eq</v-icon>
        <v-icon>location_disabled</v-icon>
        <v-icon>location_searching</v-icon>
        <v-icon>network_cell</v-icon>
        <v-icon>network_wifi</v-icon>
        <v-icon>nfc</v-icon>
        <v-icon>screen_lock_landscape</v-icon>
        <v-icon>screen_lock_portrait</v-icon>
        <v-icon>screen_lock_rotation</v-icon>
        <v-icon>screen_rotation</v-icon>
        <v-icon>sd_storage</v-icon>
        <v-icon>settings_system_daydream</v-icon>
        <v-icon>signal_cellular_4_bar</v-icon>
        <v-icon>signal_cellular_connected_no_internet_4_bar</v-icon>
        <v-icon>signal_cellular_no_sim</v-icon>
        <v-icon>signal_cellular_null</v-icon>
        <v-icon>signal_cellular_off</v-icon>
        <v-icon>signal_wifi_4_bar</v-icon>
        <v-icon>signal_wifi_4_bar_lock</v-icon>
        <v-icon>signal_wifi_off</v-icon>
        <v-icon>storage</v-icon>
        <v-icon>usb</v-icon>
        <v-icon>wallpaper</v-icon>
        <v-icon>wifi_lock</v-icon>
        <v-icon>wifi_tethering</v-icon>
      </card>
      <card :title="'Editor icons'">
        <v-icon>attach_file</v-icon>
        <v-icon>attach_money</v-icon>
        <v-icon>border_all</v-icon>
        <v-icon>border_bottom</v-icon>
        <v-icon>border_clear</v-icon>
        <v-icon>border_color</v-icon>
        <v-icon>border_horizontal</v-icon>
        <v-icon>border_inner</v-icon>
        <v-icon>border_left</v-icon>
        <v-icon>border_outer</v-icon>
        <v-icon>border_right</v-icon>
        <v-icon>border_style</v-icon>
        <v-icon>border_top</v-icon>
        <v-icon>border_vertical</v-icon>
        <v-icon>bubble_chart</v-icon>
        <v-icon>drag_handle</v-icon>
        <v-icon>format_align_center</v-icon>
        <v-icon>format_align_justify</v-icon>
        <v-icon>format_align_left</v-icon>
        <v-icon>format_align_right</v-icon>
        <v-icon>format_bold</v-icon>
        <v-icon>format_clear</v-icon>
        <v-icon>format_color_fill</v-icon>
        <v-icon>format_color_reset</v-icon>
        <v-icon>format_color_text</v-icon>
        <v-icon>format_indent_decrease</v-icon>
        <v-icon>format_indent_increase</v-icon>
        <v-icon>format_italic</v-icon>
        <v-icon>format_line_spacing</v-icon>
        <v-icon>format_list_bulleted</v-icon>
        <v-icon>format_list_numbered</v-icon>
        <v-icon>format_paint</v-icon>
        <v-icon>format_quote</v-icon>
        <v-icon>format_shapes</v-icon>
        <v-icon>format_size</v-icon>
        <v-icon>format_strikethrough</v-icon>
        <v-icon>format_textdirection_l_to_r</v-icon>
        <v-icon>format_textdirection_r_to_l</v-icon>
        <v-icon>format_underline</v-icon>
        <v-icon>functions</v-icon>
        <v-icon>highlight</v-icon>
        <v-icon>insert_chart</v-icon>
        <v-icon>insert_comment</v-icon>
        <v-icon>insert_drive_file</v-icon>
        <v-icon>insert_emoticon</v-icon>
        <v-icon>insert_invitation</v-icon>
        <v-icon>insert_link</v-icon>
        <v-icon>insert_photo</v-icon>
        <v-icon>linear_scale</v-icon>
        <v-icon>merge_type</v-icon>
        <v-icon>mode_comment</v-icon>
        <v-icon>mode_edit</v-icon>
        <v-icon>monetization_on</v-icon>
        <v-icon>money_off</v-icon>
        <v-icon>multiline_chart</v-icon>
        <v-icon>pie_chart</v-icon>
        <v-icon>pie_chart_outline</v-icon>
        <v-icon>publish</v-icon>
        <v-icon>short_text</v-icon>
        <v-icon>show_chart</v-icon>
        <v-icon>space_bar</v-icon>
        <v-icon>strikethrough_s</v-icon>
        <v-icon>text_fields</v-icon>
        <v-icon>title</v-icon>
        <v-icon>vertical_align_bottom</v-icon>
        <v-icon>vertical_align_center</v-icon>
        <v-icon>vertical_align_top</v-icon>
        <v-icon>wrap_text</v-icon>
      </card>
      <card :title="'File icons'">
        <v-icon>attachment</v-icon>
        <v-icon>cloud</v-icon>
        <v-icon>cloud_circle</v-icon>
        <v-icon>cloud_done</v-icon>
        <v-icon>cloud_download</v-icon>
        <v-icon>cloud_off</v-icon>
        <v-icon>cloud_queue</v-icon>
        <v-icon>cloud_upload</v-icon>
        <v-icon>create_new_folder</v-icon>
        <v-icon>file_download</v-icon>
        <v-icon>file_upload</v-icon>
        <v-icon>folder</v-icon>
        <v-icon>folder_open</v-icon>
        <v-icon>folder_shared</v-icon>
      </card>
      <card :title="'Hardware icons'">
        <v-icon>cast</v-icon>
        <v-icon>cast_connected</v-icon>
        <v-icon>computer</v-icon>
        <v-icon>desktop_mac</v-icon>
        <v-icon>desktop_windows</v-icon>
        <v-icon>device_hub</v-icon>
        <v-icon>devices_other</v-icon>
        <v-icon>dock</v-icon>
        <v-icon>gamepad</v-icon>
        <v-icon>headset</v-icon>
        <v-icon>headset_mic</v-icon>
        <v-icon>keyboard</v-icon>
        <v-icon>keyboard_arrow_down</v-icon>
        <v-icon>keyboard_arrow_left</v-icon>
        <v-icon>keyboard_arrow_right</v-icon>
        <v-icon>keyboard_arrow_up</v-icon>
        <v-icon>keyboard_backspace</v-icon>
        <v-icon>keyboard_capslock</v-icon>
        <v-icon>keyboard_hide</v-icon>
        <v-icon>keyboard_return</v-icon>
        <v-icon>keyboard_tab</v-icon>
        <v-icon>keyboard_voice</v-icon>
        <v-icon>laptop</v-icon>
        <v-icon>laptop_chromebook</v-icon>
        <v-icon>laptop_mac</v-icon>
        <v-icon>laptop_windows</v-icon>
        <v-icon>memory</v-icon>
        <v-icon>mouse</v-icon>
        <v-icon>phone_android</v-icon>
        <v-icon>phone_iphone</v-icon>
        <v-icon>phonelink</v-icon>
        <v-icon>phonelink_off</v-icon>
        <v-icon>power_input</v-icon>
        <v-icon>router</v-icon>
        <v-icon>scanner</v-icon>
        <v-icon>security</v-icon>
        <v-icon>sim_card</v-icon>
        <v-icon>smartphone</v-icon>
        <v-icon>speaker</v-icon>
        <v-icon>speaker_group</v-icon>
        <v-icon>tablet</v-icon>
        <v-icon>tablet_android</v-icon>
        <v-icon>tablet_mac</v-icon>
        <v-icon>toys</v-icon>
        <v-icon>tv</v-icon>
        <v-icon>watch</v-icon>
      </card>
      <card :title="'Image icons'">
        <v-icon>add_a_photo</v-icon>
        <v-icon>add_to_photos</v-icon>
        <v-icon>adjust</v-icon>
        <v-icon>assistant_photo</v-icon>
        <v-icon>audiotrack</v-icon>
        <v-icon>blur_circular</v-icon>
        <v-icon>blur_linear</v-icon>
        <v-icon>blur_off</v-icon>
        <v-icon>blur_on</v-icon>
        <v-icon>brightness_1</v-icon>
        <v-icon>brightness_2</v-icon>
        <v-icon>brightness_3</v-icon>
        <v-icon>brightness_4</v-icon>
        <v-icon>brightness_5</v-icon>
        <v-icon>brightness_6</v-icon>
        <v-icon>brightness_7</v-icon>
        <v-icon>broken_image</v-icon>
        <v-icon>brush</v-icon>
        <v-icon>burst_mode</v-icon>
        <v-icon>camera</v-icon>
        <v-icon>camera_alt</v-icon>
        <v-icon>camera_front</v-icon>
        <v-icon>camera_rear</v-icon>
        <v-icon>camera_roll</v-icon>
        <v-icon>center_focus_strong</v-icon>
        <v-icon>center_focus_weak</v-icon>
        <v-icon>collections</v-icon>
        <v-icon>collections_bookmark</v-icon>
        <v-icon>color_lens</v-icon>
        <v-icon>colorize</v-icon>
        <v-icon>compare</v-icon>
        <v-icon>control_point</v-icon>
        <v-icon>control_point_duplicate</v-icon>
        <v-icon>crop</v-icon>
        <v-icon>crop_16_9</v-icon>
        <v-icon>crop_3_2</v-icon>
        <v-icon>crop_5_4</v-icon>
        <v-icon>crop_7_5</v-icon>
        <v-icon>crop_din</v-icon>
        <v-icon>crop_free</v-icon>
        <v-icon>crop_landscape</v-icon>
        <v-icon>crop_original</v-icon>
        <v-icon>crop_portrait</v-icon>
        <v-icon>crop_rotate</v-icon>
        <v-icon>crop_square</v-icon>
        <v-icon>dehaze</v-icon>
        <v-icon>details</v-icon>
        <v-icon>edit</v-icon>
        <v-icon>exposure</v-icon>
        <v-icon>exposure_neg_1</v-icon>
        <v-icon>exposure_neg_2</v-icon>
        <v-icon>exposure_plus_1</v-icon>
        <v-icon>exposure_plus_2</v-icon>
        <v-icon>exposure_zero</v-icon>
        <v-icon>filter</v-icon>
        <v-icon>filter_1</v-icon>
        <v-icon>filter_2</v-icon>
        <v-icon>filter_3</v-icon>
        <v-icon>filter_4</v-icon>
        <v-icon>filter_5</v-icon>
        <v-icon>filter_6</v-icon>
        <v-icon>filter_7</v-icon>
        <v-icon>filter_8</v-icon>
        <v-icon>filter_9</v-icon>
        <v-icon>filter_9_plus</v-icon>
        <v-icon>filter_b_and_w</v-icon>
        <v-icon>filter_center_focus</v-icon>
        <v-icon>filter_drama</v-icon>
        <v-icon>filter_frames</v-icon>
        <v-icon>filter_hdr</v-icon>
        <v-icon>filter_none</v-icon>
        <v-icon>filter_tilt_shift</v-icon>
        <v-icon>filter_vintage</v-icon>
        <v-icon>flare</v-icon>
        <v-icon>flash_auto</v-icon>
        <v-icon>flash_off</v-icon>
        <v-icon>flash_on</v-icon>
        <v-icon>flip</v-icon>
        <v-icon>gradient</v-icon>
        <v-icon>grain</v-icon>
        <v-icon>grid_off</v-icon>
        <v-icon>grid_on</v-icon>
        <v-icon>hdr_off</v-icon>
        <v-icon>hdr_on</v-icon>
        <v-icon>hdr_strong</v-icon>
        <v-icon>hdr_weak</v-icon>
        <v-icon>healing</v-icon>
        <v-icon>image</v-icon>
        <v-icon>image_aspect_ratio</v-icon>
        <v-icon>iso</v-icon>
        <v-icon>landscape</v-icon>
        <v-icon>leak_add</v-icon>
        <v-icon>leak_remove</v-icon>
        <v-icon>lens</v-icon>
        <v-icon>linked_camera</v-icon>
        <v-icon>looks</v-icon>
        <v-icon>looks_3</v-icon>
        <v-icon>looks_4</v-icon>
        <v-icon>looks_5</v-icon>
        <v-icon>looks_6</v-icon>
        <v-icon>looks_one</v-icon>
        <v-icon>looks_two</v-icon>
        <v-icon>loupe</v-icon>
        <v-icon>monochrome_photos</v-icon>
        <v-icon>movie_creation</v-icon>
        <v-icon>movie_filter</v-icon>
        <v-icon>music_note</v-icon>
        <v-icon>nature</v-icon>
        <v-icon>nature_people</v-icon>
        <v-icon>navigate_before</v-icon>
        <v-icon>navigate_next</v-icon>
        <v-icon>palette</v-icon>
        <v-icon>panorama</v-icon>
        <v-icon>panorama_fisheye</v-icon>
        <v-icon>panorama_horizontal</v-icon>
        <v-icon>panorama_vertical</v-icon>
        <v-icon>panorama_wide_angle</v-icon>
        <v-icon>photo</v-icon>
        <v-icon>photo_album</v-icon>
        <v-icon>photo_camera</v-icon>
        <v-icon>photo_filter</v-icon>
        <v-icon>photo_library</v-icon>
        <v-icon>photo_size_select_actual</v-icon>
        <v-icon>photo_size_select_large</v-icon>
        <v-icon>photo_size_select_small</v-icon>
        <v-icon>picture_as_pdf</v-icon>
        <v-icon>portrait</v-icon>
        <v-icon>remove_red_eye</v-icon>
        <v-icon>rotate_90_degrees_ccw</v-icon>
        <v-icon>rotate_left</v-icon>
        <v-icon>rotate_right</v-icon>
        <v-icon>slideshow</v-icon>
        <v-icon>straighten</v-icon>
        <v-icon>style</v-icon>
        <v-icon>switch_camera</v-icon>
        <v-icon>switch_video</v-icon>
        <v-icon>tag_faces</v-icon>
        <v-icon>texture</v-icon>
        <v-icon>timelapse</v-icon>
        <v-icon>timer</v-icon>
        <v-icon>timer_10</v-icon>
        <v-icon>timer_3</v-icon>
        <v-icon>timer_off</v-icon>
        <v-icon>tonality</v-icon>
        <v-icon>transform</v-icon>
        <v-icon>tune</v-icon>
        <v-icon>view_comfy</v-icon>
        <v-icon>view_compact</v-icon>
        <v-icon>vignette</v-icon>
        <v-icon>wb_auto</v-icon>
        <v-icon>wb_cloudy</v-icon>
        <v-icon>wb_incandescent</v-icon>
        <v-icon>wb_sunny</v-icon>
      </card>
      <card :title="'Maps icons'">
        <v-icon>add_location</v-icon>
        <v-icon>beenhere</v-icon>
        <v-icon>directions</v-icon>
        <v-icon>directions_bike</v-icon>
        <v-icon>directions_bus</v-icon>
        <v-icon>directions_car</v-icon>
        <v-icon>directions_ferry</v-icon>
        <v-icon>directions_subway</v-icon>
        <v-icon>directions_train</v-icon>
        <v-icon>directions_transit</v-icon>
        <v-icon>directions_walk</v-icon>
        <v-icon>edit_location</v-icon>
        <v-icon>ev_station</v-icon>
        <v-icon>flight</v-icon>
        <v-icon>hotel</v-icon>
        <v-icon>layers</v-icon>
        <v-icon>layers_clear</v-icon>
        <v-icon>local_activity</v-icon>
        <v-icon>local_airport</v-icon>
        <v-icon>local_atm</v-icon>
        <v-icon>local_bar</v-icon>
        <v-icon>local_cafe</v-icon>
        <v-icon>local_car_wash</v-icon>
        <v-icon>local_convenience_store</v-icon>
        <v-icon>local_dining</v-icon>
        <v-icon>local_drink</v-icon>
        <v-icon>local_florist</v-icon>
        <v-icon>local_gas_station</v-icon>
        <v-icon>local_grocery_store</v-icon>
        <v-icon>local_hospital</v-icon>
        <v-icon>local_hotel</v-icon>
        <v-icon>local_laundry_service</v-icon>
        <v-icon>local_library</v-icon>
        <v-icon>local_mall</v-icon>
        <v-icon>local_movies</v-icon>
        <v-icon>local_offer</v-icon>
        <v-icon>local_parking</v-icon>
        <v-icon>local_pharmacy</v-icon>
        <v-icon>local_phone</v-icon>
        <v-icon>local_pizza</v-icon>
        <v-icon>local_play</v-icon>
        <v-icon>local_post_office</v-icon>
        <v-icon>local_print_shop</v-icon>
        <v-icon>local_restaurant</v-icon>
        <v-icon>local_see</v-icon>
        <v-icon>local_shipping</v-icon>
        <v-icon>local_taxi</v-icon>
        <v-icon>map</v-icon>
        <v-icon>my_location</v-icon>
        <v-icon>navigation</v-icon>
        <v-icon>near_me</v-icon>
        <v-icon>person_pin_circle</v-icon>
        <v-icon>person_pin</v-icon>
        <v-icon>pin_drop</v-icon>
        <v-icon>place</v-icon>
        <v-icon>rate_review</v-icon>
        <v-icon>restaurant</v-icon>
        <v-icon>restaurant_menu</v-icon>
        <v-icon>satellite</v-icon>
        <v-icon>store_mall_directory</v-icon>
        <v-icon>streetview</v-icon>
        <v-icon>subway</v-icon>
        <v-icon>terrain</v-icon>
        <v-icon>traffic</v-icon>
        <v-icon>train</v-icon>
        <v-icon>tram</v-icon>
        <v-icon>transfer_within_a_station</v-icon>
        <v-icon>zoom_out_map</v-icon>
      </card>
      <card :title="'Navigation icons'">
        <v-icon>apps</v-icon>
        <v-icon>arrow_back</v-icon>
        <v-icon>arrow_downward</v-icon>
        <v-icon>arrow_drop_down</v-icon>
        <v-icon>arrow_drop_down_circle</v-icon>
        <v-icon>arrow_drop_up</v-icon>
        <v-icon>arrow_forward</v-icon>
        <v-icon>arrow_upwards</v-icon>
        <v-icon>cancel</v-icon>
        <v-icon>check</v-icon>
        <v-icon>chevron_left</v-icon>
        <v-icon>chevron_right</v-icon>
        <v-icon>close</v-icon>
        <v-icon>expand_less</v-icon>
        <v-icon>expand_more</v-icon>
        <v-icon>first_page</v-icon>
        <v-icon>fullscreen</v-icon>
        <v-icon>fullscreen_exit</v-icon>
        <v-icon>last_page</v-icon>
        <v-icon>menu</v-icon>
        <v-icon>more_horiz</v-icon>
        <v-icon>more_vert</v-icon>
        <v-icon>refresh</v-icon>
        <v-icon>subdirectory_arrow_left</v-icon>
        <v-icon>subdirectory_arrow_right</v-icon>
        <v-icon>adb</v-icon>
        <v-icon>airline_seat_flat</v-icon>
        <v-icon>airline_seat_individual_suite</v-icon>
        <v-icon>airline_seat_legroom_extra</v-icon>
        <v-icon>airline_seat_legroom_normal</v-icon>
        <v-icon>airline_seat_legroom_reduced</v-icon>
        <v-icon>airline_seat_recline_extra</v-icon>
        <v-icon>airline_seat_recline_normal</v-icon>
        <v-icon>bluetooth_audio</v-icon>
        <v-icon>confirvion_number</v-icon>
        <v-icon>disc_full</v-icon>
        <v-icon>do_not_disturb</v-icon>
        <v-icon>do_not_disturb_alt</v-icon>
        <v-icon>do_not_disturb_off</v-icon>
        <v-icon>do_not_disturb_on</v-icon>
        <v-icon>drive_eta</v-icon>
        <v-icon>enhanced_encryption</v-icon>
        <v-icon>event_available</v-icon>
        <v-icon>event_busy</v-icon>
        <v-icon>event_note</v-icon>
        <v-icon>folder_special</v-icon>
        <v-icon>live_tv</v-icon>
        <v-icon>mms</v-icon>
        <v-icon>more</v-icon>
        <v-icon>network_check</v-icon>
        <v-icon>network_locked</v-icon>
        <v-icon>no_encryption</v-icon>
        <v-icon>ondemand_video</v-icon>
        <v-icon>personal_video</v-icon>
        <v-icon>phone_bluetooth_speaker</v-icon>
        <v-icon>phone_forwarded</v-icon>
        <v-icon>phone_in_talk</v-icon>
        <v-icon>phone_locked</v-icon>
        <v-icon>phone_missed</v-icon>
        <v-icon>phone_paused</v-icon>
        <v-icon>power</v-icon>
        <v-icon>priority_high</v-icon>
        <v-icon>sd_card</v-icon>
        <v-icon>sim_card_alert</v-icon>
        <v-icon>sms</v-icon>
        <v-icon>sms_failed</v-icon>
        <v-icon>sync</v-icon>
        <v-icon>sync_disabled</v-icon>
        <v-icon>sync_problem</v-icon>
        <v-icon>system_update</v-icon>
        <v-icon>tap_and_play</v-icon>
        <v-icon>time_to_leave</v-icon>
        <v-icon>vibration</v-icon>
        <v-icon>voice_chat</v-icon>
        <v-icon>vpn_lock</v-icon>
        <v-icon>wc</v-icon>
        <v-icon>wifi</v-icon>
      </card>
      <card :title="'Places icons'">
        <v-icon>ac_unit</v-icon>
        <v-icon>airport_shuttle</v-icon>
        <v-icon>all_inclusive</v-icon>
        <v-icon>beach_access</v-icon>
        <v-icon>business_center</v-icon>
        <v-icon>casino</v-icon>
        <v-icon>child_care</v-icon>
        <v-icon>fitness_center</v-icon>
        <v-icon>free_breakfast</v-icon>
        <v-icon>golf_course</v-icon>
        <v-icon>hot_tub</v-icon>
        <v-icon>kitchen</v-icon>
        <v-icon>pool</v-icon>
        <v-icon>room_service</v-icon>
        <v-icon>rv_hookup</v-icon>
        <v-icon>smoke_free</v-icon>
        <v-icon>spa</v-icon>
      </card>
      <card :title="'Social icons'">
        <v-icon>cake</v-icon>
        <v-icon>domain</v-icon>
        <v-icon>group</v-icon>
        <v-icon>group_add</v-icon>
        <v-icon>location_city</v-icon>
        <v-icon>mood</v-icon>
        <v-icon>mood_bad</v-icon>
        <v-icon>notifications</v-icon>
        <v-icon>notifications_none</v-icon>
        <v-icon>notifications_off</v-icon>
        <v-icon>notifications_active</v-icon>
        <v-icon>notifications_paused</v-icon>
        <v-icon>pages</v-icon>
        <v-icon>party_mode</v-icon>
        <v-icon>people</v-icon>
        <v-icon>people_outline</v-icon>
        <v-icon>person</v-icon>
        <v-icon>person_add</v-icon>
        <v-icon>person_outline</v-icon>
        <v-icon>plus_one</v-icon>
        <v-icon>poll</v-icon>
        <v-icon>public</v-icon>
        <v-icon>school</v-icon>
        <v-icon>sentiment_dissatisfied</v-icon>
        <v-icon>sentiment_neutral</v-icon>
        <v-icon>sentiment_satisfied</v-icon>
        <v-icon>sentiment_very_dissatisfied</v-icon>
        <v-icon>sentiment_very_satisfied</v-icon>
        <v-icon>share</v-icon>
        <v-icon>whatshot</v-icon>
      </card>
      <card :title="'Toggle icons'" class="mb-0">
        <v-icon>check_box</v-icon>
        <v-icon>check_box_outline_blank</v-icon>
        <v-icon>indeterminate_check_box</v-icon>
        <v-icon>radio_button_unchecked</v-icon>
        <v-icon>radio_button_checked</v-icon>
        <v-icon>star</v-icon>
        <v-icon>star_half</v-icon>
        <v-icon>star_border</v-icon>
      </card>
    </div>
</template>

<script>
import card from '../../card/card'
export default {
  name: 'icon',
  components: {
    card
  }
}
</script>

<style scoped lang="scss">
@import '../../../assets/sass/variable';
.v-icon {
  background: rgba(main-color(A100),.2);
  font-size: 32px;
  height: 50px;
  padding: 9px;
  margin: 11px 10px;
  overflow: hidden;
  text-align: center;
  width: 50px;
  color: black;
}
</style>
